### ISSUE TITLE
请问您现在依然在使用这个程序吗？

### ISSUE THREAD

**Issue by bo369** [tkliuxing/bookspider#2]
想问下您现在的线上情况。
另外，不知您这套程序是否允许免费使用？
多谢。

**Comment by tkliuxing** [comment]
是的,在用. 在线的站点: [kanxiaoshuo.me](http://www.kanxiaoshuo.me)
这个项目使用 Apache License 授权,请随意取用.

PS: 非代码错误请使用邮件联络,谢谢
