### ISSUE TITLE
 python manage.py syncdb错误

### ISSUE THREAD

**Issue by JohanWangE** [tkliuxing/bookspider#3]
大侠：
        在ubuntu 14.04上按照你的说明配置完环境，运行 python manage.py syncdb，报
/usr/local/lib/python2.7/dist-packages/threadedcomments/models.py:120: RemovedInDjango18Warning: `PublicThreadedCommentManager.get_query_set` method should be renamed `get_queryset`.
  class PublicThreadedCommentManager(ThreadedCommentManager):

CommandError: System check identified some issues:

ERRORS:
threadedcomments.ThreadedComment.user: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
	HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

何解？

**Comment by tkliuxing** [comment]
遵循提示查找问题就好：
HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
